Update and cleanup

diff --git a/functions/funced b/functions/funced
--- a/functions/funced
+++ b/functions/funced
@@ -1,28 +1,31 @@
+#!/bin/zsh
 ##? funced - edit the function specified
 
-#function funced {
-
-local ZFUNCDIR="${ZFUNCDIR:-${ZDOTDIR:-$HOME/.config/zsh}/functions}"
+local ZFUNCDIR="${ZFUNCDIR:-${ZDOTDIR:-${XDG_CONFIG_HOME:-$HOME/.config}/zsh}/functions}"
 
 # check args
 if [[ -z "$1" ]]; then
   echo >&2 "funced: Expected function name argument"
   return 1
 elif [[ ! -d "$ZFUNCDIR" ]]; then
-  echo >&2 "funced: Directory not found '$ZFUNCDIR'."
+  echo >&2 "funced: Zsh function directory not found '$ZFUNCDIR'."
   return 1
 fi
 
 # new function definition: make a file template
 if [[ ! -f "$ZFUNCDIR/$1" ]]; then
-  local -a tmpl=(
-    '#!/bin/zsh'
-    "##? $1 - description"
-    "#function $1 {"
-    ''
-    '#}'
-  )
-  printf "%s\n" "${(@)tmpl}" >"$ZFUNCDIR/$1"
+  cat <<EOS > "$ZFUNCDIR/$1"
+#!/bin/zsh
+##? TODO: Add description. Use ##? comments for funchelp docs.
+
+###
+### TODO: write your autoload function here.
+### WARNING: Do not add a 'function $1() {}' wrapper for autoloads.
+###
+
+# vim: ft=zsh sw=2 ts=2 et
+
+EOS
   autoload -Uz "$ZFUNCDIR/$1"
 fi
 
@@ -32,7 +35,3 @@ if [[ -n "$VISUAL" ]]; then
 else
   ${EDITOR:-vim} "$ZFUNCDIR/$1"
 fi
-
-#}
-
-# vim: ft=zsh sw=2 ts=2 et
diff --git a/functions/funcsave b/functions/funcsave
--- a/functions/funcsave
+++ b/functions/funcsave
@@ -1,8 +1,7 @@
+#!/bin/zsh
 ##? funcsave - save a function to $ZFUNCDIR for lazy loading
 
-#function funcsave {
-
-local ZFUNCDIR="${ZFUNCDIR:-${ZDOTDIR:-$HOME/.config/zsh}/functions}"
+local ZFUNCDIR="${ZFUNCDIR:-${ZDOTDIR:-${XDG_CONFIG_HOME:-$HOME/.config}/zsh}/functions}"
 
 # check args
 if [[ -z "$1" ]]; then
@@ -12,7 +11,7 @@ elif ! typeset -f "$1" > /dev/null; then
   echo >&2 "funcsave: Unknown function '$1'"
   return 1
 elif [[ ! -d "$ZFUNCDIR" ]]; then
-  echo >&2 "funced: Directory not found '$ZFUNCDIR'."
+  echo >&2 "funcsave: Zsh function directory not found '$ZFUNCDIR'."
   return 1
 fi
 
@@ -21,7 +20,3 @@ autoload +X "$1" > /dev/null
 
 # remove first/last lines (ie: 'function foo {' and '}') and de-indent one level
 type -f "$1" | awk 'NR>2 {print prev} {gsub(/^\t/, "", $0); prev=$0}' >| "$ZFUNCDIR/$1"
-
-#}
-
-# vim: ft=zsh sw=2 ts=2 et
