Refactor

diff --git a/functions/funced b/functions/funced
--- a/functions/funced
+++ b/functions/funced
@@ -1,20 +1,53 @@
-### funced
-# edit the function specified
+##? funced - edit the function specified
 
-ZFUNCDIR="${ZFUNCDIR:-${ZDOTDIR:-$HOME/.config/zsh}/functions}"
+#function funced {
+
+local ZFUNCDIR="${ZFUNCDIR:-${ZDOTDIR:-$HOME/.config/zsh}/functions}"
 
 # check args
 if [[ -z "$1" ]]; then
-  echo "funced: Expected function name argument" >&2 && return 1
+  echo >&2 "funced: Expected function name argument"
+  return 1
+elif [[ ! -d "$ZFUNCDIR" ]]; then
+  echo >&2 "funced: Directory not found '$ZFUNCDIR'."
+  return 1
 fi
 
 # new function definition: make a file template
 if [[ ! -f "$ZFUNCDIR/$1" ]]; then
-  cat <<eos > "$ZFUNCDIR/$1"
-# Add function internals here.
-# Do NOT include function definition (ie: omit 'function $1() {').
-# See: http://zsh.sourceforge.net/Doc/Release/Functions.html#Autoloading-Functions
-eos
+  cat <<EOS > "$ZFUNCDIR/$1"
+##############################################################################
+# TODO: Remove this header block
+# Do NOT include function definition block (ie: omit 'function $1() { }').
+# See: https://zsh.sourceforge.io/Doc/Release/Functions.html#Autoloading-Functions
+#
+# Use ##? comments for help/usage docs.
+##############################################################################
+
+##? $1 - TODO: add description here
+##?
+##? usage: $1 [-h|--help]
+##?        $1 [<options>] <arguments>
+
+#function $1 {
+
+local -a o_help
+zmodload zsh/zutil
+zparseopts -D -F -K -- \
+  {h,-help}=o_help ||
+  return 1
+
+if (( \$#o_help )); then
+  funchelp "$1"
+  return
+fi
+
+# TODO: write your function here
+
+#}
+
+EOS
+  autoload -Uz "$ZFUNCDIR/$1"
 fi
 
 # open the function file
@@ -23,3 +56,7 @@ if [[ -z "$VISUAL" ]]; then
 else
   ${EDITOR:-vim} "$ZFUNCDIR/$1"
 fi
+
+#}
+
+# vim: ft=zsh sw=2 ts=2 et
diff --git a/functions/funcsave b/functions/funcsave
--- a/functions/funcsave
+++ b/functions/funcsave
@@ -1,11 +1,19 @@
-### funcsave
-# save a function to $ZFUNCDIR for lazy loading
+##? funcsave - save a function to $ZFUNCDIR for lazy loading
+
+#function funcsave {
+
+local ZFUNCDIR="${ZFUNCDIR:-${ZDOTDIR:-$HOME/.config/zsh}/functions}"
 
 # check args
 if [[ -z "$1" ]]; then
-  echo "funcsave: Expected function name argument" >&2 && return 1
+  echo >&2 "funcsave: Expected function name argument"
+  return 1
 elif ! typeset -f "$1" > /dev/null; then
-  echo "funcsave: Unknown function '$1'" >&2 && return 1
+  echo >&2 "funcsave: Unknown function '$1'"
+  return 1
+elif [[ ! -d "$ZFUNCDIR" ]]; then
+  echo >&2 "funced: Directory not found '$ZFUNCDIR'."
+  return 1
 fi
 
 # make sure the function is loaded in case it's already lazy
@@ -13,3 +21,7 @@ autoload +X "$1" > /dev/null
 
 # remove first/last lines (ie: 'function foo {' and '}') and de-indent one level
 type -f "$1" | awk 'NR>2 {print prev} {gsub(/^\t/, "", $0); prev=$0}' >| "$ZFUNCDIR/$1"
+
+#}
+
+# vim: ft=zsh sw=2 ts=2 et
